# Generated by Django 4.2.11 on 2024-03-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qam', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qam.project'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a case name.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(help_text='Enter a case_number.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description.', max_length=1000, null=True)),
                ('expected_result', models.CharField(blank=True, help_text='Enter an expected_result.', max_length=255, null=True)),
                ('init_conf', models.TextField(blank=True, help_text='Enter an initial configuration.', max_length=1000, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qam.project')),
            ],
            options={
                'ordering': ['case_number'],
            },
        ),
    ]
