# Generated by Django 4.2.11 on 2024-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qam', '0003_alter_product_project_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='products',
            field=models.ManyToManyField(help_text='Select a product for this case.', to='qam.product'),
        ),
    ]
