# Generated by Django 4.2.11 on 2024-03-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qam', '0006_alter_case_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='project',
        ),
    ]
