# Generated by Django 4.2.11 on 2024-03-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qam', '0007_remove_case_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('p', 'PASSED'), ('f', 'FAILED'), ('r', 'PASSED_WITH_REMARKS'), ('b', 'BLOCKED'), ('n', 'N.A.')], default='n', help_text='Report result.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fail_reason', models.CharField(blank=True, help_text='Enter fail reason.', max_length=255, null=True)),
                ('fail_location', models.CharField(blank=True, help_text='Enter fail location.', max_length=255, null=True)),
                ('info_link', models.CharField(blank=True, help_text='Enter info link.', max_length=255, null=True)),
                ('params', models.CharField(blank=True, help_text='Enter params.', max_length=255, null=True)),
                ('info', models.CharField(blank=True, help_text='Enter info.', max_length=255, null=True)),
                ('reboot', models.BooleanField(blank=True, default=False, help_text='Enter reboot.', null=True)),
                ('fast', models.BooleanField(blank=True, default=False, help_text='Enter fast.', null=True)),
                ('login', models.BooleanField(blank=True, default=False, help_text='Enter login.', null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qam.case')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='qam.version')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
