version: "3.8"
services:
  # Mysql database container
  db:
    build: ./mysql
    container_name: mysqldb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qam
      MYSQL_USER: qam
      MYSQL_PASSWORD: qam
      MYSQL_ROOT_PASSWORD: qam
      TZ: Europe/Sofia
    networks:
      - qam

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: qam
    networks:
      - qam

networks:
  qam:

volumes:
  db-data: